spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/user_inf
    password: postgres
    username: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/user_inf
    password: postgres
    user: postgres
    locations: classpath:db/migration